version: '3'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8081:8080"
    command:
      - start-dev